version: 0.0
os: linux
files:
  - source: src/
    destination: /var/www/html/
hooks:
  ApplicationStop:
    - location: scripts/httpd_stop.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/httpd_start.sh
      timeout: 300
      runas: root

